blogapp/blogapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('blogs/', include('blogs.urls')),
    path('admin/', admin.site.urls),

    # REST FRAMEWORK
    path('api-auth/', include('rest_framework.urls')),

    path('api/', include('blogs.api.urls', 'blog_api')),
]

blogapp/blogs/api/urls.py
from blogs.api import views
from django.urls import path

app_name = 'blog'
urlpatterns = [
    # Blogs

    path('blogs/', views.BlogList.as_view(), name="blogs"),
    path('blogs/<int:pk>', views.DetailBlog.as_view(), name="detail-blog"),

    # Categories
    path('categories/', views.CategoriesList.as_view(), name="categories"),
    path('categories/<int:pk>', views.DetailCategory.as_view(),
         name="detail-category"),

    # Users
    path('users/', views.UserList.as_view(), name="users"),
    path('users/<int:pk>', views.DetailUser.as_view(), name="detail-user")
]

blogapp/blogs/urls.py
from django.urls import path
from . import views

app_name = "blogs"
urlpatterns = [
    path('',  views.IndexView.as_view(), name="index"),
    path('<int:pk>/', views.DetailView.as_view(), name="detail"),
    path('categories/<int:pk>/', views.CategoryBlogsView.as_view(), name="category"),
    # path('<int:pk>/', views.like, name="like"),
]

blogapp/blogs/models.py
from django.db import models
from django.utils import timezone
# Create your models here.


class Category(models.Model):
    title = models.CharField(max_length=50)

    def __str__(self):
        return f"{self.title}"


class User(models.Model):
    username = models.CharField(max_length=100)
    password = models.CharField(max_length=100)
    fullname = models.CharField(max_length=100, null=True)
    email = models.EmailField(max_length=100, null=True)
    date_of_birth = models.DateField(null=True)
    created_date = models.DateTimeField(default=timezone.now())

    def __str__(self):
        return f"{self.username}"


class Blog(models.Model):
    img = models.ImageField(null=True)
    title = models.CharField(max_length=50)
    content = models.TextField(max_length=500)
    pub_date = models.DateTimeField(default=timezone.now())
    likes = models.IntegerField(default=0)
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, default=0)
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return f"{self.title}"

blogapp/blogs/api/views.py
from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from rest_framework.parsers import JSONParser
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.decorators import api_view
from blogs.models import Blog, Category, User
from blogs.api.serializers import BlogSerializer, CategorySerializer, UserSerializer


# Category
class CategoriesList(APIView):
    """
        List all categories, create new categories
    """

    def get(self, request, format=None):
        cates = Category.objects.all()
        serializer = CategorySerializer(cates, many=True)
        return Response(serializer.data)

    def post(self, request, format=None):
        serializer = CategorySerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=201)
        return Response(serializer.errors, status=400)


class DetailCategory(APIView):
    """
        get detail category by id, delete and update that category
    """

    def get_object(self, pk):
        try:
            return Category.objects.get(pk=pk)
        except Category.DoesNotExist:
            raise Response(status=404)

    def get(self, request, pk, format=None):
        cate = self.get_object(pk)
        serializer = CategorySerializer(cate)
        return Response(serializer.data)

    def put(self, request, pk, format=None):
        cate = self.get_object(pk)
        serializer = CategorySerializer(cate, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=400)

    def delete(self, request, pk, format=None):
        cate = self.get_object(pk)
        data = {}
        if cate.delete():
            data['delete'] = "Delete successful"
        return Response(data, status=204)


# Blog
class BlogList(APIView):
    """
        list all blogs, and create new blog
    """

    def get(self, request, format=None):
        blogs = Blog.objects.all()
        serializer = BlogSerializer(blogs, many=True)
        return Response(serializer.data)

    def post(self, request, format=None):
        serializer = BlogSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(status=404)


class DetailBlog(APIView):
    """
        get detail of one blog by id, delelete and update that blog
    """

    def get_object(self, pk):
        try:
            return Blog.objects.get(pk=pk)
        except Blog.DoesNotExist:
            Response(status=404)

    def get(self, request, pk, format=None):
        blog = self.get_object(pk)
        serializer = BlogSerializer(blog)
        return Response(serializer.data)

    def put(self, request, pk, format=None):
        blog = self.get_object(pk)
        serializer = BlogSerializer(blog, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=400)

    def delete(self, request, pk, format=None):
        blog = self.get_object(pk)
        data = {}
        if blog.delete():
            data['delete'] = "Delete successful"
        return Response(data, status=200)


# User
class UserList(APIView):
    """
        get list users and create new user
    """

    def get(self, request, format=None):
        user = User.objects.all()
        serializer = UserSerializer(user, many=True)
        return Response(serializer.data)

    def post(self, request, format=None):
        serializer = UserSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=200)
        return Response(status=404)


class DetailUser(APIView):
    def get_object(self, pk):
        try:
            return User.objects.get(pk=pk)
        except User.DoesNotExist:
            return Response(status=404)

    def get(self, request, pk, format=None):
        user = self.get_object(pk)
        serializer = UserSerializer(user)
        return Response(serializer.data, status=200)

    def put(self, request, pk, format=None):
        user = self.get_object(pk)
        serializer = UserSerializer(user, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=200)
        return Response(serializer.errors, status=400)

    def delete(self, request, pk, format=None):
        user = self.get_object(pk)
        data = {}
        user.delete()
        data['delete'] = "Delete successful"
        return Response(data, status=200)

blogapp/blogs/views.py
from django.shortcuts import render
from .models import Blog, Category
from django.utils import timezone
from django.urls import reverse
from django.views import generic

# Create your views here.


class IndexView(generic.ListView):
    """
        List all blogs and categories
    """
    template_name = "blogs/index.html"
    context_object_name = "blogs"

    def get_queryset(self):
        """ Return the list blogs """
        return Blog.objects.all().order_by('-pub_date')

    def get_context_data(self):
        context = super().get_context_data()
        context["cates"] = Category.objects.all()
        return context


class DetailView(generic.DetailView):
    """
        get detail of one blog by id
    """
    model = Blog
    template_name = "blogs/detail.html"


class CategoryBlogsView(generic.ListView):
    """
        get all blogs of one category by id
    """
    template_name = "blogs/category.html"
    context_object_name = "categories"

    def get_queryset(self):
        return Category.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['blogs'] = Category.objects.get(
            pk=self.kwargs['pk']).blog_set.all()
        return context


# def like(request, blog_id):
#     """
#         like a post
#     """
#     blog = Blog.objects.get(pk=blog_id)
#     like = request.POST['likes']
#     like += 1
#     like.save()
#     context = {
#         "blog": blog
#     }
#     return render(request, "blogs/detail.html", context)

blogapp/blogs/templates/blogs/base.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>BLOG APP</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
        integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>

<body>
    <!--HEADER-->
    <div class="container">
        <header class="py-3">
            <div class="row flex-nowrap justify-content-between align-item center">
                <div class="col-4 pt-1">
                    <a href="#" class="link-secondary">Subcribe</a>
                </div>
                <div class="col-4 text-center">
                    <a href="{% url 'blogs:index' %}" class="text-dark fs-2">
                        HOME
                    </a>
                </div>

                <div class="col-4 d-flex justify-content-end align-items center">
                    <a href="" class="btn btn-sm btn-outline-secondary">Sign up</a>
                </div>
            </div>
            <hr />
        </header>

        <!---NAVIGATION-->
        <div class="py-1 mb-2">
            <div class="nav d-flex justify-content-between">
                {% block category %}
                {% endblock %}
            </div>
        </div>
    </div>
    <div class="container">


        {% block content %}

        {% endblock %}

        {% block detail %}
        {% endblock %}
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>

    <script src="{% static 'blogs/index.js' %}">

    </script>

</body>

</html>

blogapp/blogs/templates/blogs/category.html
{% extends 'blogs/base.html' %}

{% block category %}
{% if categories %}
{% for cate in categories %}
<a href="{% url 'blogs:category' cate.id %}" class="p-2 link-secondary">{{cate}}</a>
{% endfor %}
{% else %}
<h3>Don't have categories to display</h3>
{% endif %}

{% endblock %}

{% block content %}
{% if blogs %}

{% for blog in blogs %}
<div class="row">
    <div class="col-md-12">
        <div style="padding:20px"
            class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
            <strong class="d-inline-block mb-2 text-primary">
                {{blog.category}} -
                {% if blog.author.fullname %}
                {{blog.author.fullname}} posted
                {% else %}
                {{blog.author.username}} posted
                {% endif %}
            </strong>
            <h3 class="mb-0">{{blog.title}}</h3>
            <div class="mb-1 text-muted">{{blog.pub_date}}</div>
            <!-- <p class="card-text mb-auto">
                {{blog.content}}
            </p> -->
            <a href="{% url 'blogs:detail' blog.id %}" class="stretched-link">Continue reading</a>
        </div>
    </div>
</div>
{% endfor %}
{% else %}
<h1>
    This categories haven't had blogs yet
</h1>
{% endif %}
{% endblock %}

blogapp/blogs/templates/blogs/detail.html
{% extends 'blogs/base.html' %}

{% block detail %}
<div class="row">
    <div class="col">
        <div class="img-post">
            <img src="{{blog.img.url}}" alt="">
        </div>
        <h3 class="pb-4 mb-4 fst-italic border-bottom">
            {{blog.title}}
        </h3>
        <p>{{blog.content}}</p>
        {% if blog.likes != 0 %}
        <div class="blog-likes">
            <span class="align-item-right fw-bold">
                {{blog.likes}} likes
            </span>
            <i class="fa-regular fa-heart" id="like_post"></i>
        </div>

        {% else %}
        <div class="blog-likes">
            <span class="fw-bold">Be the first one to like the post</span>

        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

blogapp/blogs/templates/blogs/index.html
{% extends 'blogs/base.html' %}

{% block category %}
{% if cates %}
{% for cate in cates %}
<a href="{% url 'blogs:category' cate.id %}" class="p-2 link-secondary">{{cate}}</a>
{% endfor %}
{% else %}
<h3>Don't have categories to display</h3>
{% endif %}
{% endblock %}

{% block content %}
<!-- <div class="p-4 p-md4 mb-5 mb-4 text-white bg-dark rounded">
    <div class="col-md-6 px-0">
        <h1 class="display-4 fst-italic">Coll featured blog post</h1>
        <p class="lead my-3">
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Atque cupiditate error voluptatibus modi
            quasi, ea, soluta, tempora unde officiis veritatis fuga repellendus at voluptas temporibus quisquam
            natus ex sequi eveniet.
        </p>
        <div class="lead mb-0">
            <a href="#" class="text-white fw-bold">Continue reading...</a>
        </div>
    </div>
</div> -->
{% if blogs %}

{% for blog in blogs %}
<div class="row">
    <div class="col-md-12">
        <div style="padding:20px"
            class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
            <strong class="d-inline-block mb-2 text-primary">
                {{blog.category}} -
                {% if blog.author.fullname %}
                {{blog.author.fullname}} posted
                {% else %}
                {{blog.author.username}} posted
                {% endif %}
            </strong>
            <h3 class="mb-0">{{blog.title}}</h3>
            <div class="mb-1 text-muted">{{blog.pub_date}}</div>
            <!-- <p class="card-text mb-auto">
                {{blog.content}}
            </p> -->
            <a href="{% url 'blogs:detail' blog.id %}" class="stretched-link">Continue reading</a>
        </div>
    </div>
</div>
{% endfor %}
{% else %}
<h1>
    Blogs haven't created yet
</h1>
{% endif %}
{% endblock %}